import type { RentalUnit } from '@/lib/types';

export const mockRentalUnits: RentalUnit[] = [
  {
    unit_id: 'cam-01',
    unit_name: 'Sony A7 IV Kit',
    category: 'Camera',
    status: 'available',
    description: 'Professional mirrorless camera with lens kit for shoots, travel, and events.',
    image_url: '',
    price_per_day: 4500,
    location: 'Quezon City',
  },
  {
    unit_id: 'cam-02',
    unit_name: 'Canon EOS R6',
    category: 'Camera',
    status: 'rented',
    description: 'High-performance hybrid camera ideal for content creators and vlogging.',
    image_url: '',
    price_per_day: 4200,
    location: 'Makati',
  },
  {
    unit_id: 'phone-01',
    unit_name: 'iPhone 15 Pro Max',
    category: 'Phone',
    status: 'available',
    description: 'Premium smartphone with pro camera system and fast mobile performance.',
    image_url: '',
    price_per_day: 2200,
    location: 'BGC',
  },
  {
    unit_id: 'vehicle-01',
    unit_name: 'Toyota Wigo 2024',
    category: 'Vehicle',
    status: 'available',
    description: 'Reliable compact vehicle for city travel, weekend trips, and daily errands.',
    image_url: '',
    price_per_day: 3200,
    location: 'Alabang',
  },
  {
    unit_id: 'laptop-01',
    unit_name: 'MacBook Pro 14-inch',
    category: 'Laptop',
    status: 'available',
    description: 'Powerful laptop for editing, development, presentations, and creative work.',
    image_url: '',
    price_per_day: 2800,
    location: 'Makati',
  },
  {
    unit_id: 'drone-01',
    unit_name: 'DJI Mini 3 Pro',
    category: 'Drone',
    status: 'rented',
    description: 'Compact aerial camera with stabilized 4K video for travel and production.',
    image_url: '',
    price_per_day: 1800,
    location: 'Pasig',
  },
];